### ISSUE TITLE
Feature: Expenses Tracker: Front End

### ISSUE THREAD

**Issue by SensibleSidekick** [AllHubs-June-2024-Liftoff/Liftoff-Doyle-Money-Matters#7]
Displays user's budget and allows user to manually enter in transactions (expenses or income). Transaction addition will be done with a button that allows you to enter an amount, select whether it is income or expense, and allow for users to tag the item for categorization.

**Comment by SensibleSidekick** [comment]
**Button to Manually Enter Transaction. Opens page showing:**

- [x] Amount - Text Field
- [x] Tags - Drop down?
- [x] Is this an income? - Checkbox (This will determine if this is an addition or subtraction)
- [x] Submit Button
